let userName=prompt("Your Name")
    console.log(userName)
    userAge=prompt("Hello,"+userName+"How old are you?")
    console.log(userAge)
    userExpe=prompt(userName+"your experience")
    console.log(userExpe)
    userPlace=prompt(userName+"Where are you from?")
    console.log(userPlace)
    userDescride=prompt(userName+"How would you describe yourself in one word?")
    console.log(userDescride)
    userWeaknesses=prompt(userName+"What are your three greatest strengths and weaknesses?")
    console.log(userWeaknesses)
    userWant=prompt(userName+"Why do you want to work with us?")
    console.log(userWant)
    userAchievent=prompt(userName+"What is your main professional achievement?")
    console.log(userAchievent)
    userProblem=prompt(userName+"Tell us about the problem or conflict you faced at work and how you dealt with it")
    console.log(userProblem)
    userFive=prompt(userName+"Where do you see yourself in five years")
    console.log(userFive)
    userDream=prompt(userName+"Tell us about your dream")
    console.log(userDream)
    userLeavejob=prompt(userName+"Why did you decide to leave your previous job")
    console.log(userLeavejob)

    // console.log(userName)
    // console.log(userAge)
    // console.log(userExpe)
    // console.log(userPlace)
    // console.log(userDescride)
    // console.log(userWeaknesses)
    // console.log(userWant)
    // console.log(userProblem)
    // console.log(userFive)
    // console.log(userDream)
    // console.log(userLeavejob)